---

- name: Download ZooKeeper archive
  ansible.builtin.get_url:
    url: "https://archive.apache.org/dist/zookeeper/zookeeper-{{ zookeeper_version }}/{{ zookeeper_install_dir | basename }}.tar.gz"
    dest: "/opt/{{ zookeeper_install_dir | basename }}.tar.gz"
    mode: '0644'

- name: Extract ZooKeeper archive
  ansible.builtin.unarchive:
    src: "/opt/{{ zookeeper_install_dir | basename }}.tar.gz"
    dest: /opt
    remote_src: yes
    creates: "{{ zookeeper_install_dir }}"  # Use 'creates' to check if extraction is necessary

- name: Create symbolic link
  ansible.builtin.file:
    src: "{{ zookeeper_install_dir }}"
    dest: "{{ zookeeper_home }}"
    state: link

- name: Set ownership of ZooKeeper directory
  ansible.builtin.file:
    path: "{{ zookeeper_install_dir }}"
    state: directory
    owner: zookeeper
    group: zookeeper
    recurse: true

- name: Copy zoo.cfg from zoo_sample.cfg
  ansible.builtin.command:
    cmd: "cp {{ zookeeper_home }}/conf/zoo_sample.cfg {{ zookeeper_home }}/conf/zoo.cfg"
  args:
    creates: "{{ zookeeper_home }}/conf/zoo.cfg"  # Use 'creates' to check if copying is necessary

- name: Update content of zoo.cfg
  template:
    src: "zoo.cfg.j2"
    dest: "{{ zookeeper_home }}/conf/zoo.cfg"
    owner: zookeeper
    group: zookeeper
    backup: true

- name: Create path for myid file
  ansible.builtin.file:
    path: "{{ zookeeper_data_dir }}"
    state: directory
    owner: zookeeper
    group: zookeeper

- name: Populate myid
  template:
    src: myid.j2
    dest: "{{ zookeeper_data_dir }}/myid"
    owner: zookeeper
    group: zookeeper

- name: Create zookeeper service
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd  # Notify the handler to reload systemd after creating the service file

- name: Flush handlers so systemd is reloaded before the service is started
  ansible.builtin.meta: flush_handlers

- name: Start zookeeper service
  ansible.builtin.systemd:
    name: zookeeper
    state: started

- name: Enable the zookeeper service to start on boot
  ansible.builtin.systemd:
    name: zookeeper
    enabled: true
