---

- name: Download Kafka archive
  ansible.builtin.get_url:
    url: "{{ kafka_url }}"
    dest: /opt
    mode: 0644

- name: Extract Kafka archive
  ansible.builtin.unarchive:
    src: /opt/kafka_{{ scala_version }}-{{ kafka_version }}.tgz
    dest: /opt
    remote_src: yes
    creates: /opt/kafka_{{ scala_version }}-{{ kafka_version }}  # Use 'creates' to check if extraction is necessary

- name: Create symbolic link
  ansible.builtin.file:
    src: /opt/kafka_{{ scala_version }}-{{ kafka_version }}
    dest: /opt/kafka
    state: link

- name: Set ownership of Kafka directory
  ansible.builtin.file:
    path: /opt/kafka
    state: directory
    owner: kafka
    group: kafka
    recurse: true

- name: Update kafka configuration file
  template:
    src: server.properties.j2
    dest: "/opt/kafka/config/server.properties"
    owner: kafka
    group: kafka

- name: Update consumer configuration file
  template:
    src: consumer.properties.j2
    dest: "/opt/kafka/config/consumer.properties"
    owner: kafka
    group: kafka

- name: Update producer configuration file
  template:
    src: producer.properties.j2
    dest: "/opt/kafka/config/producer.properties"
    owner: kafka
    group: kafka

- name: Update kafka-run-class.sh
  ansible.builtin.lineinfile:
    path: /opt/kafka/bin/kafka-run-class.sh
    line: "JAVA_HOME={{ java_home }}"
    insertbefore: '^if \[ \$# -lt 1 \];'
    #insertbefore: "BOF"
    state: present

- name: Update zookeeper-server-start.sh set javaopts
  template:
    src: zookeeper-server-start.sh.j2
    dest: "/opt/kafka/bin/zookeeper-server-start.sh"
    owner: kafka
    group: kafka

- name: Create kafka service
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd  # Notify the handler to reload systemd after creating the service file

- name: Start kafka service
  ansible.builtin.systemd:
    name: kafka
    state: started

- name: Enable the kafka service to start on boot
  ansible.builtin.systemd:
    name: kafka
    enabled: true