# Cluster a 3 nodi: ogni nodo ospita sia ZooKeeper sia un broker Kafka
# (stessa topologia del documento di riferimento SASL_SSL + SCRAM-SHA-512).
#
# Il nome dell'host in inventory coincide con l'hostname del nodo perche'
# viene usato come CN e come SAN DNS.1 nei certificati X.509 dei broker.

[zookeeper]
kafka-zkp-p01 ansible_host=10.109.15.84 zookeeper_myid=1
kafka-zkp-p02 ansible_host=10.109.15.85 zookeeper_myid=2
kafka-zkp-p03 ansible_host=10.109.15.86 zookeeper_myid=3

[kafka]
kafka-zkp-p01 ansible_host=10.109.15.84 broker_id=1
kafka-zkp-p02 ansible_host=10.109.15.85 broker_id=2
kafka-zkp-p03 ansible_host=10.109.15.86 broker_id=3

[all:vars]
ansible_user=root
